cmd: gcloud
name: "Deploy to Gcloud"
args:
  - app
  - deploy
sh: true,
# cwd: <current working directory for `cmd`>
# env:
#   VARIABLE1: "VALUE1"
#   VARIABLE2: "VALUE2"
# errorMatch:
#   - ^regexp1$
#   - ^regexp2$
# warningMatch:
#   - ^regexp1$
#   - ^regexp2$
# keymap: <keymap string>
# atomCommandName: namespace:command
# targets:
#   pypi:
#       cmd: twine
#       args:
#         - upload
#         - dist/*
#   deploy:
#       # (any previous options are viable here except `targets` itself)
